;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        easy-kill
        ensime-mouse-motion
        haskell-indentation-common-electric-command
        kill-region
        sp-backward-delete-char
        suspend-frame
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        backward-kill-sentence
        beginning-of-buffer
        end-of-buffer
        haskell-indentation-newline-and-indent
        indent-for-tab-command
        markdown-outdent-or-delete
        xref-pop-marker-stack
        ))
